[package]
name = "web-scraper-v2"
description = "nice"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenvy = "0.15.7"
feed-rs = "1.5.2"
rayon = "1.10.0"
reqwest = {version = "0.12.4", default-features = false, features = ["rustls-tls", "blocking"]}
scraper = "0.19.0"
sqlx = {version = "0.7.4", features = [ "runtime-tokio", "tls-rustls", "postgres", "chrono" ] }
tokio = { version = "1.37.0", features = ["full"] }
