[package]
name = "web-scraper-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
feed-rs = "1.5.2"
rayon = "1.10.0"
reqwest = {version = "0.12.4", features = ["blocking"]}
scraper = "0.19.0"
sqlx = "0.7.4"
tokio = { version = "1.37.0", features = ["full", "rt"] }
